name: Repository Events
on:
  push:
    branches:
      - main
      - "feature/*"       # matches feature/featA, feature/featB, does not match feature/featA/FeatB
      - "feature/**"      # matches feature/featA, feature/featB, and feature/featA/FeatB
      - "!feature/featA"  # that filter will exclude the feature/featA branch
    tags:
      - v1.*              # match v1.1, v1.1.2
      - "!v.1.1.1"
    paths:
      - "**.js"
      - "!app.js"
  pull_request:
    types: [opened, assigned, reopened, synchronize]
    branches:
      - main
    paths:
      - "**.js"
  issues:
    types: [opened]
jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3
