name: Validate the JDK Public Action
on: [push]

jobs:
  jdk-test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17.0.9"
          distribution: "temurin"
          cache: "maven"
